# Copyright (c) 2021 AccelByte Inc. All Rights Reserved.
# This is licensed software from AccelByte Inc, for limitations
# and restrictions contact your company contract manager.
#
# Code generated. DO NOT EDIT!

# template file: accelbyte_cloud_py_codegen

"""Auto-generated package that contains models used by the AccelByte Cloud Cloudsave Service."""

__version__ = "3.6.1"
__author__ = "AccelByte"
__email__ = "dev@accelbyte.net"

# pylint: disable=line-too-long

# admin_concurrent_record
from .wrappers import admin_put_game_record_concurrent_handler_v1
from .wrappers import admin_put_game_record_concurrent_handler_v1_async
from .wrappers import admin_put_player_public_record_concurrent_handler_v1
from .wrappers import admin_put_player_public_record_concurrent_handler_v1_async
from .wrappers import admin_put_player_record_concurrent_handler_v1
from .wrappers import admin_put_player_record_concurrent_handler_v1_async

# admin_game_record
from .wrappers import admin_delete_game_record_handler_v1
from .wrappers import admin_delete_game_record_handler_v1_async
from .wrappers import admin_get_game_record_handler_v1
from .wrappers import admin_get_game_record_handler_v1_async
from .wrappers import admin_post_game_record_handler_v1
from .wrappers import admin_post_game_record_handler_v1_async
from .wrappers import admin_put_game_record_handler_v1
from .wrappers import admin_put_game_record_handler_v1_async
from .wrappers import list_game_records_handler_v1
from .wrappers import list_game_records_handler_v1_async

# admin_player_record
from .wrappers import admin_delete_player_public_record_handler_v1
from .wrappers import admin_delete_player_public_record_handler_v1_async
from .wrappers import admin_delete_player_record_handler_v1
from .wrappers import admin_delete_player_record_handler_v1_async
from .wrappers import admin_get_player_public_record_handler_v1
from .wrappers import admin_get_player_public_record_handler_v1_async
from .wrappers import admin_get_player_record_handler_v1
from .wrappers import admin_get_player_record_handler_v1_async
from .wrappers import admin_get_player_record_size_handler_v1
from .wrappers import admin_get_player_record_size_handler_v1_async
from .wrappers import admin_post_player_public_record_handler_v1
from .wrappers import admin_post_player_public_record_handler_v1_async
from .wrappers import admin_post_player_record_handler_v1
from .wrappers import admin_post_player_record_handler_v1_async
from .wrappers import admin_put_player_public_record_handler_v1
from .wrappers import admin_put_player_public_record_handler_v1_async
from .wrappers import admin_put_player_record_handler_v1
from .wrappers import admin_put_player_record_handler_v1_async
from .wrappers import admin_retrieve_player_records
from .wrappers import admin_retrieve_player_records_async
from .wrappers import bulk_get_player_record_size_handler_v1
from .wrappers import bulk_get_player_record_size_handler_v1_async
from .wrappers import list_player_record_handler_v1
from .wrappers import list_player_record_handler_v1_async

# concurrent_record
from .wrappers import put_game_record_concurrent_handler_v1
from .wrappers import put_game_record_concurrent_handler_v1_async
from .wrappers import put_player_public_record_concurrent_handler_v1
from .wrappers import put_player_public_record_concurrent_handler_v1_async
from .wrappers import put_player_record_concurrent_handler_v1
from .wrappers import put_player_record_concurrent_handler_v1_async

# public_game_record
from .wrappers import delete_game_record_handler_v1
from .wrappers import delete_game_record_handler_v1_async
from .wrappers import get_game_record_handler_v1
from .wrappers import get_game_record_handler_v1_async
from .wrappers import get_game_records_bulk
from .wrappers import get_game_records_bulk_async
from .wrappers import post_game_record_handler_v1
from .wrappers import post_game_record_handler_v1_async
from .wrappers import put_game_record_handler_v1
from .wrappers import put_game_record_handler_v1_async

# public_player_record
from .wrappers import bulk_get_player_public_record_handler_v1
from .wrappers import bulk_get_player_public_record_handler_v1_async
from .wrappers import delete_player_record_handler_v1
from .wrappers import delete_player_record_handler_v1_async
from .wrappers import get_player_public_record_handler_v1
from .wrappers import get_player_public_record_handler_v1_async
from .wrappers import get_player_record_handler_v1
from .wrappers import get_player_record_handler_v1_async
from .wrappers import get_player_records_bulk_handler_v1
from .wrappers import get_player_records_bulk_handler_v1_async
from .wrappers import post_player_public_record_handler_v1
from .wrappers import post_player_public_record_handler_v1_async
from .wrappers import post_player_record_handler_v1
from .wrappers import post_player_record_handler_v1_async
from .wrappers import public_delete_player_public_record_handler_v1
from .wrappers import public_delete_player_public_record_handler_v1_async
from .wrappers import put_player_public_record_handler_v1
from .wrappers import put_player_public_record_handler_v1_async
from .wrappers import put_player_record_handler_v1
from .wrappers import put_player_record_handler_v1_async
from .wrappers import retrieve_player_records
from .wrappers import retrieve_player_records_async
