"""Auto-generated top-level package for the justice-cloudsave-service."""

__version__ = "1.9.0"
__author__ = "AccelByte"
__email__ = "dev@accelbyte.net"

# pylint: disable=line-too-long

# admin_game_record
from .wrappers import admin_delete_game_record_handler_v1
from .wrappers import admin_delete_game_record_handler_v1_async
from .wrappers import admin_get_game_record_handler_v1
from .wrappers import admin_get_game_record_handler_v1_async
from .wrappers import admin_post_game_record_handler_v1
from .wrappers import admin_post_game_record_handler_v1_async
from .wrappers import admin_put_game_record_handler_v1
from .wrappers import admin_put_game_record_handler_v1_async
from .wrappers import list_game_records_handler_v1
from .wrappers import list_game_records_handler_v1_async

# admin_player_record
from .wrappers import admin_delete_player_public_record_handler_v1
from .wrappers import admin_delete_player_public_record_handler_v1_async
from .wrappers import admin_delete_player_record_handler_v1
from .wrappers import admin_delete_player_record_handler_v1_async
from .wrappers import admin_get_player_public_record_handler_v1
from .wrappers import admin_get_player_public_record_handler_v1_async
from .wrappers import admin_get_player_record_handler_v1
from .wrappers import admin_get_player_record_handler_v1_async
from .wrappers import admin_post_player_public_record_handler_v1
from .wrappers import admin_post_player_public_record_handler_v1_async
from .wrappers import admin_post_player_record_handler_v1
from .wrappers import admin_post_player_record_handler_v1_async
from .wrappers import admin_put_player_public_record_handler_v1
from .wrappers import admin_put_player_public_record_handler_v1_async
from .wrappers import admin_put_player_record_handler_v1
from .wrappers import admin_put_player_record_handler_v1_async
from .wrappers import list_player_record_handler_v1
from .wrappers import list_player_record_handler_v1_async

# concurrent_record
from .wrappers import put_game_record_concurrent_handler_v1
from .wrappers import put_game_record_concurrent_handler_v1_async
from .wrappers import put_player_public_record_concurrent_handler_v1
from .wrappers import put_player_public_record_concurrent_handler_v1_async

# public_game_record
from .wrappers import delete_game_record_handler_v1
from .wrappers import delete_game_record_handler_v1_async
from .wrappers import get_game_record_handler_v1
from .wrappers import get_game_record_handler_v1_async
from .wrappers import post_game_record_handler_v1
from .wrappers import post_game_record_handler_v1_async
from .wrappers import put_game_record_handler_v1
from .wrappers import put_game_record_handler_v1_async

# public_player_record
from .wrappers import delete_player_record_handler_v1
from .wrappers import delete_player_record_handler_v1_async
from .wrappers import get_player_public_record_handler_v1
from .wrappers import get_player_public_record_handler_v1_async
from .wrappers import get_player_record_handler_v1
from .wrappers import get_player_record_handler_v1_async
from .wrappers import post_player_public_record_handler_v1
from .wrappers import post_player_public_record_handler_v1_async
from .wrappers import post_player_record_handler_v1
from .wrappers import post_player_record_handler_v1_async
from .wrappers import public_delete_player_public_record_handler_v1
from .wrappers import public_delete_player_public_record_handler_v1_async
from .wrappers import put_player_public_record_handler_v1
from .wrappers import put_player_public_record_handler_v1_async
from .wrappers import put_player_record_handler_v1
from .wrappers import put_player_record_handler_v1_async
