# pylint: disable=line-too-long

from .get_game_record_handler_v1 import GetGameRecordHandlerV1
from .put_game_record_handler_v1 import PutGameRecordHandlerV1
from .post_game_record_handler_v1 import PostGameRecordHandlerV1
from .delete_game_record_handler_v1 import DeleteGameRecordHandlerV1
