version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "crud-stat-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zfli4f0dlsbn"
s3_prefix = "crud-stat-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
