from ._protected_save_events_game_telemetry_v1_protected_events_post import protected_save_events_game_telemetry_v1_protected_events_post
from ._protected_get_playtime_game_telemetry_v1_protected_steam_ids_steam_id_playtime_get import protected_get_playtime_game_telemetry_v1_protected_steam_ids_steam_id_playtime_get
from ._protected_update_playtime_game_telemetry_v1_protected_steam_ids_steam_id_playtime_playtime_put import protected_update_playtime_game_telemetry_v1_protected_steam_ids_steam_id_playtime_playtime_put


commands = [
    protected_save_events_game_telemetry_v1_protected_events_post,
    protected_get_playtime_game_telemetry_v1_protected_steam_ids_steam_id_playtime_get,
    protected_update_playtime_game_telemetry_v1_protected_steam_ids_steam_id_playtime_playtime_put,
]
