# pylint: disable=line-too-long

from .list_game_records_handler_v1 import ListGameRecordsHandlerV1
from .get_game_record_handler_by_key_v1 import GetGameRecordHandlerByKeyV1
from .put_admin_game_record_handler_v1 import PutAdminGameRecordHandlerV1
from .post_admin_game_record_handler_v1 import PostAdminGameRecordHandlerV1
from .delete_admin_game_record_handler_v1 import DeleteAdminGameRecordHandlerV1
