# Copyright (c) 2021 AccelByte Inc. All Rights Reserved.
# This is licensed software from AccelByte Inc, for limitations
# and restrictions contact your company contract manager.
# 
# Code generated. DO NOT EDIT!

# template file: justice_py_sdk_codegen/__main__.py

"""Auto-generated package that contains models used by the Analytics Game Telemetry."""

__version__ = "0.0.1"
__author__ = "AccelByte"
__email__ = "dev@accelbyte.net"

# pylint: disable=line-too-long

from ._gametelemetry_operations import admin_get_events_game_telemetry_v1_admin_events_get
from ._gametelemetry_operations import admin_get_events_game_telemetry_v1_admin_events_get_async
from ._gametelemetry_operations import admin_get_namespace_game_telemetry_v1_admin_telemetrynamespace_get
from ._gametelemetry_operations import admin_get_namespace_game_telemetry_v1_admin_telemetrynamespace_get_async
from ._gametelemetry_operations import protected_get_playtime_game_telemetry_v1_protected_steam_ids_steam_id_playtime_get
from ._gametelemetry_operations import protected_get_playtime_game_telemetry_v1_protected_steam_ids_steam_id_playtime_get_async
from ._gametelemetry_operations import protected_save_events_game_telemetry_v1_protected_events_post
from ._gametelemetry_operations import protected_save_events_game_telemetry_v1_protected_events_post_async
from ._gametelemetry_operations import protected_update_playtime_game_telemetry_v1_protected_steam_ids_steam_id_playtime_playtime_put
from ._gametelemetry_operations import protected_update_playtime_game_telemetry_v1_protected_steam_ids_steam_id_playtime_playtime_put_async
