# pylint: disable=line-too-long

from .get_clients import GetClients
from .create_client import CreateClient
from .get_client import GetClient
from .update_client import UpdateClient
from .delete_client import DeleteClient
from .update_client_permission import UpdateClientPermission
from .add_client_permission import AddClientPermission
from .delete_client_permission import DeleteClientPermission
from .update_client_secret import UpdateClientSecret
from .get_clientsby_namespace import GetClientsbyNamespace
from .create_client_by_namespace import CreateClientByNamespace
from .delete_client_by_namespace import DeleteClientByNamespace
from .admin_get_clients_by_namespace_v3 import AdminGetClientsByNamespaceV3
from .admin_create_client_v3 import AdminCreateClientV3
from .admin_get_clientsby_namespaceby_idv3 import AdminGetClientsbyNamespacebyIDV3
from .admin_delete_client_v3 import AdminDeleteClientV3
from .admin_update_client_v3 import AdminUpdateClientV3
from .admin_update_client_permission_v3 import AdminUpdateClientPermissionV3
from .admin_add_client_permissions_v3 import AdminAddClientPermissionsV3
from .admin_delete_client_permission_v3 import AdminDeleteClientPermissionV3
