# Copyright (c) 2021 AccelByte Inc. All Rights Reserved.
# This is licensed software from AccelByte Inc, for limitations
# and restrictions contact your company contract manager.
#
# Code generated. DO NOT EDIT!

# template file: accelbyte_cloud_py_codegen

"""Auto-generated package that contains models used by the AccelByte Cloud Leaderboard Service."""

__version__ = "2.15.9"
__author__ = "AccelByte"
__email__ = "dev@accelbyte.net"

# pylint: disable=line-too-long

# leaderboard_configuration
from .wrappers import create_leaderboard_configuration_admin_v1
from .wrappers import create_leaderboard_configuration_admin_v1_async
from .wrappers import create_leaderboard_configuration_public_v1
from .wrappers import create_leaderboard_configuration_public_v1_async
from .wrappers import delete_bulk_leaderboard_configuration_admin_v1
from .wrappers import delete_bulk_leaderboard_configuration_admin_v1_async
from .wrappers import delete_leaderboard_configuration_admin_v1
from .wrappers import delete_leaderboard_configuration_admin_v1_async
from .wrappers import get_leaderboard_configuration_admin_v1
from .wrappers import get_leaderboard_configuration_admin_v1_async
from .wrappers import get_leaderboard_configurations_admin_v1
from .wrappers import get_leaderboard_configurations_admin_v1_async
from .wrappers import get_leaderboard_configurations_public_v1
from .wrappers import get_leaderboard_configurations_public_v1_async
from .wrappers import get_leaderboard_configurations_public_v2
from .wrappers import get_leaderboard_configurations_public_v2_async
from .wrappers import update_leaderboard_configuration_admin_v1
from .wrappers import update_leaderboard_configuration_admin_v1_async

# leaderboard_data
from .wrappers import admin_get_archived_leaderboard_ranking_data_v1_handler
from .wrappers import admin_get_archived_leaderboard_ranking_data_v1_handler_async
from .wrappers import create_archived_leaderboard_ranking_data_v1_handler
from .wrappers import create_archived_leaderboard_ranking_data_v1_handler_async
from .wrappers import delete_user_ranking_admin_v1
from .wrappers import delete_user_ranking_admin_v1_async
from .wrappers import delete_user_ranking_public_v1
from .wrappers import delete_user_ranking_public_v1_async
from .wrappers import delete_user_rankings_admin_v1
from .wrappers import delete_user_rankings_admin_v1_async
from .wrappers import get_all_time_leaderboard_ranking_admin_v1
from .wrappers import get_all_time_leaderboard_ranking_admin_v1_async
from .wrappers import get_all_time_leaderboard_ranking_public_v1
from .wrappers import get_all_time_leaderboard_ranking_public_v1_async
from .wrappers import get_all_time_leaderboard_ranking_public_v2
from .wrappers import get_all_time_leaderboard_ranking_public_v2_async
from .wrappers import get_archived_leaderboard_ranking_data_v1_handler
from .wrappers import get_archived_leaderboard_ranking_data_v1_handler_async
from .wrappers import get_current_month_leaderboard_ranking_admin_v1
from .wrappers import get_current_month_leaderboard_ranking_admin_v1_async
from .wrappers import get_current_month_leaderboard_ranking_public_v1
from .wrappers import get_current_month_leaderboard_ranking_public_v1_async
from .wrappers import get_current_season_leaderboard_ranking_admin_v1
from .wrappers import get_current_season_leaderboard_ranking_admin_v1_async
from .wrappers import get_current_season_leaderboard_ranking_public_v1
from .wrappers import get_current_season_leaderboard_ranking_public_v1_async
from .wrappers import get_current_week_leaderboard_ranking_admin_v1
from .wrappers import get_current_week_leaderboard_ranking_admin_v1_async
from .wrappers import get_current_week_leaderboard_ranking_public_v1
from .wrappers import get_current_week_leaderboard_ranking_public_v1_async
from .wrappers import get_today_leaderboard_ranking_admin_v1
from .wrappers import get_today_leaderboard_ranking_admin_v1_async
from .wrappers import get_today_leaderboard_ranking_public_v1
from .wrappers import get_today_leaderboard_ranking_public_v1_async
from .wrappers import get_user_ranking_admin_v1
from .wrappers import get_user_ranking_admin_v1_async
from .wrappers import get_user_ranking_public_v1
from .wrappers import get_user_ranking_public_v1_async
from .wrappers import update_user_point_admin_v1
from .wrappers import update_user_point_admin_v1_async

# user_data
from .wrappers import get_user_leaderboard_rankings_admin_v1
from .wrappers import get_user_leaderboard_rankings_admin_v1_async

# user_visibility
from .wrappers import get_hidden_users_v2
from .wrappers import get_hidden_users_v2_async
from .wrappers import get_user_visibility_status_v2
from .wrappers import get_user_visibility_status_v2_async
from .wrappers import set_user_leaderboard_visibility_status_v2
from .wrappers import set_user_leaderboard_visibility_status_v2_async
from .wrappers import set_user_visibility_status_v2
from .wrappers import set_user_visibility_status_v2_async
