# Copyright (c) 2021 AccelByte Inc. All Rights Reserved.
# This is licensed software from AccelByte Inc, for limitations
# and restrictions contact your company contract manager.
#
# Code generated. DO NOT EDIT!

# template file: accelbyte_cloud_py_codegen

"""Auto-generated package that contains models used by the AccelByte Cloud Leaderboard Service."""

__version__ = "2.19.0"
__author__ = "AccelByte"
__email__ = "dev@accelbyte.net"

# pylint: disable=line-too-long

from ._leaderboard_configuration import create_leaderboard_configuration_admin_v1
from ._leaderboard_configuration import create_leaderboard_configuration_admin_v1_async
from ._leaderboard_configuration import create_leaderboard_configuration_public_v1
from ._leaderboard_configuration import create_leaderboard_configuration_public_v1_async
from ._leaderboard_configuration import delete_bulk_leaderboard_configuration_admin_v1
from ._leaderboard_configuration import (
    delete_bulk_leaderboard_configuration_admin_v1_async,
)
from ._leaderboard_configuration import delete_leaderboard_configuration_admin_v1
from ._leaderboard_configuration import delete_leaderboard_configuration_admin_v1_async
from ._leaderboard_configuration import get_leaderboard_configuration_admin_v1
from ._leaderboard_configuration import get_leaderboard_configuration_admin_v1_async
from ._leaderboard_configuration import get_leaderboard_configurations_admin_v1
from ._leaderboard_configuration import get_leaderboard_configurations_admin_v1_async
from ._leaderboard_configuration import get_leaderboard_configurations_public_v1
from ._leaderboard_configuration import get_leaderboard_configurations_public_v1_async
from ._leaderboard_configuration import get_leaderboard_configurations_public_v2
from ._leaderboard_configuration import get_leaderboard_configurations_public_v2_async
from ._leaderboard_configuration import update_leaderboard_configuration_admin_v1
from ._leaderboard_configuration import update_leaderboard_configuration_admin_v1_async

from ._leaderboard_data import admin_get_archived_leaderboard_ranking_data_v1_handler
from ._leaderboard_data import (
    admin_get_archived_leaderboard_ranking_data_v1_handler_async,
)
from ._leaderboard_data import create_archived_leaderboard_ranking_data_v1_handler
from ._leaderboard_data import create_archived_leaderboard_ranking_data_v1_handler_async
from ._leaderboard_data import delete_user_ranking_admin_v1
from ._leaderboard_data import delete_user_ranking_admin_v1_async
from ._leaderboard_data import delete_user_ranking_public_v1
from ._leaderboard_data import delete_user_ranking_public_v1_async
from ._leaderboard_data import delete_user_rankings_admin_v1
from ._leaderboard_data import delete_user_rankings_admin_v1_async
from ._leaderboard_data import get_all_time_leaderboard_ranking_admin_v1
from ._leaderboard_data import get_all_time_leaderboard_ranking_admin_v1_async
from ._leaderboard_data import get_all_time_leaderboard_ranking_public_v1
from ._leaderboard_data import get_all_time_leaderboard_ranking_public_v1_async
from ._leaderboard_data import get_all_time_leaderboard_ranking_public_v2
from ._leaderboard_data import get_all_time_leaderboard_ranking_public_v2_async
from ._leaderboard_data import get_archived_leaderboard_ranking_data_v1_handler
from ._leaderboard_data import get_archived_leaderboard_ranking_data_v1_handler_async
from ._leaderboard_data import get_current_month_leaderboard_ranking_admin_v1
from ._leaderboard_data import get_current_month_leaderboard_ranking_admin_v1_async
from ._leaderboard_data import get_current_month_leaderboard_ranking_public_v1
from ._leaderboard_data import get_current_month_leaderboard_ranking_public_v1_async
from ._leaderboard_data import get_current_season_leaderboard_ranking_admin_v1
from ._leaderboard_data import get_current_season_leaderboard_ranking_admin_v1_async
from ._leaderboard_data import get_current_season_leaderboard_ranking_public_v1
from ._leaderboard_data import get_current_season_leaderboard_ranking_public_v1_async
from ._leaderboard_data import get_current_week_leaderboard_ranking_admin_v1
from ._leaderboard_data import get_current_week_leaderboard_ranking_admin_v1_async
from ._leaderboard_data import get_current_week_leaderboard_ranking_public_v1
from ._leaderboard_data import get_current_week_leaderboard_ranking_public_v1_async
from ._leaderboard_data import get_today_leaderboard_ranking_admin_v1
from ._leaderboard_data import get_today_leaderboard_ranking_admin_v1_async
from ._leaderboard_data import get_today_leaderboard_ranking_public_v1
from ._leaderboard_data import get_today_leaderboard_ranking_public_v1_async
from ._leaderboard_data import get_user_ranking_admin_v1
from ._leaderboard_data import get_user_ranking_admin_v1_async
from ._leaderboard_data import get_user_ranking_public_v1
from ._leaderboard_data import get_user_ranking_public_v1_async
from ._leaderboard_data import update_user_point_admin_v1
from ._leaderboard_data import update_user_point_admin_v1_async

from ._user_data import get_user_leaderboard_rankings_admin_v1
from ._user_data import get_user_leaderboard_rankings_admin_v1_async

from ._user_visibility import get_hidden_users_v2
from ._user_visibility import get_hidden_users_v2_async
from ._user_visibility import get_user_visibility_status_v2
from ._user_visibility import get_user_visibility_status_v2_async
from ._user_visibility import set_user_leaderboard_visibility_status_v2
from ._user_visibility import set_user_leaderboard_visibility_status_v2_async
from ._user_visibility import set_user_visibility_status_v2
from ._user_visibility import set_user_visibility_status_v2_async
