# pylint: disable=line-too-long

from .delete_namespace_slot_config import DeleteNamespaceSlotConfig
from .delete_user_slot_config import DeleteUserSlotConfig
from .get_namespace_slot_config import GetNamespaceSlotConfig
from .get_user_slot_config import GetUserSlotConfig
from .update_namespace_slot_config import UpdateNamespaceSlotConfig
from .update_user_slot_config import UpdateUserSlotConfig
