# pylint: disable=line-too-long

from .admin_delete_player_public_record_handler_v1 import AdminDeletePlayerPublicRecordHandlerV1
from .admin_delete_player_record_handler_v1 import AdminDeletePlayerRecordHandlerV1
from .admin_get_player_public_record_handler_v1 import AdminGetPlayerPublicRecordHandlerV1
from .admin_get_player_record_handler_v1 import AdminGetPlayerRecordHandlerV1
from .admin_post_player_public_record_handler_v1 import AdminPostPlayerPublicRecordHandlerV1
from .admin_post_player_record_handler_v1 import AdminPostPlayerRecordHandlerV1
from .admin_put_player_public_record_handler_v1 import AdminPutPlayerPublicRecordHandlerV1
from .admin_put_player_record_handler_v1 import AdminPutPlayerRecordHandlerV1
from .list_player_record_handler_v1 import ListPlayerRecordHandlerV1
