# template file: justice_py_sdk_codegen/__main__.py

# pylint: disable=line-too-long

from .protected_get_playtime__9a0e17 import ProtectedGetPlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimeGet
from .protected_save_events_g_832bbb import ProtectedSaveEventsGameTelemetryV1ProtectedEventsPost
from .protected_update_playti_4b5b85 import ProtectedUpdatePlaytimeGameTelemetryV1ProtectedSteamIdsSteamIdPlaytimePlaytimePut
